# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 유형찬
title: JAVA 백엔드 주니어 개발자
email: gudcks305@gmail.com
website: https://velog.io/@gudcks0305

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  gudcks0305
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/hc1.jpg
about_content: | # this will include new lines to allow paragraphs
  JAVA & Spring , 주니어 개발자로 현재 GDSC DJU 라는 동아리에서 백엔드 개발자로 내부 서비스를 구축 및 관리하고 있습니다. 
  
  OCI , AWS 등을 이용하여 Spring 기반 웹 서버를 배포 하여 TECH Blog , ADMIN 서비스를 관리 중에 있습니다. 
  
  현재는 동아리 내에서 후배 개발자들을 이끌어주는 <mark>서포터</mark>로서 활동 중이며 같은 진로의 개발자들을 위한 개념 퀴즈 , 스터디등으로 도움을 주고 있습니다.
  
  개발자는 꾸준하고 지속적으로 성장해야한다는 마음가짐으로 매일 적은 성과라고 하더라도 <mark>1일 1커밋</mark>을 실천 하고 있습니다. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: GDSC_TECH_BLOG
        link: github.com/GDSC-Daejin/GDSC-WEB-BackEnd
        caption:  2022.02 - 2022.09
        # link_text: Project Website
        additional_links:
          - title: GDSC_TECH_BLOG
            icon: fab fa-github
            url: github.com/GDSC-Daejin/GDSC-WEB-BackEnd
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          2021년도 9월 GDSC DJU가 0기 모집을 실시하며 이후 진행한 프로젝트 및 스터디 활동을 자체 제작 사이트에 기록하기 위해 만든 BLOG 사이트 입니다.
          프론트 3명 , 백엔드 3명 , 디자이너 3명이 진행한 프로젝트 입니다.
          <mark>Stack</mark> : Java | Spring | Mysql | OCI 
        description: | # this will include new lines to allow paragraphs
            - OCI 플랫폼을 이용하여 학생 개발자 동아리 서버 비용 부담을 최소화
            - 최초로 외부 인원이 지속적으로 사용하는 서버를 제작 
            - 프론트 로컬 환경에서의 Cookies CORS 문제 해결 -> local 환경 Https , domain 도입 
            - 지속적인 서비스를 진행함에 따라 지속적인 코드 개선을 진행 중 입니다.
      - layout: left
        title: GDSC_MSA 아키텍쳐 이전
        link: github.com/GDSC-Daejin/GDSC-DJU-MSA
        caption:  2022.05 - 2022.09
        # link_text: Project Website
        additional_links:
          - title: GDSC_TECH_BLOG
            icon: fab fa-github
            url: github.com/GDSC-Daejin/GDSC-DJU-MSA
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          GDSC 내부에서 진행 중인 프로젝트의 양이 점점 증가하고 동일한 DB , 서비스를 쉽게 확장 할 수 있도록 기존 MVC 패턴의 단일 서버에서 MSA 프로젝트로 구조를 변경 하였습니다.
          <mark>Stack</mark> : Java | Spring | Mysql | OCI | Spring Netflix | Eureka
        description: | # this will include new lines to allow paragraphs
          - Spring Gateway를 통한 API 통신 
          - 추가 서비스 API에 도메인 할당 불필요 
          - 서버의 확장을 수직적인 구조에서 수평적인 구조로 변경하며 동아리 내 <mark>서버 부담 감소</mark>에 기여 
          - 각각의 서비스를 나누어 관리할 수 있게 됨에 따라 <mark>유지보수의 능률 상승</mark>에 기여 
          - 지속적인 서비스를 진행함에 따라 지속적인 코드 개선을 진행 중 입니다.
  - title: 외부 활동 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Google Developer Student Clubs - Daejin University
        link: https://web.gdsc-dju.com/
        # link_text: boringcompany.com
        sub_title: Member
        caption:  2021.09 - Present
        quote: >
          Google Developer Student Clubs (GDSC) 프로그램은 학생들이 개발/리더십 능력을 키울 수 있도록 지원하는 프로그램입니다. 기술적 성장을 위한 교육자료를 제공하고 리더십 개발을 위한 다양한 활동들을 지원합니다.
        description: | # this will include new lines to allow paragraphs
          - 2주 간격 정기 세션을 통해 지식 공유을 했습니다.  
          - 프로젝트 협업을 통해서 기존에 잘 몰랐던 GIT Flow 지식과 에자일 모델 같은 개발 방법론에 대한 지식 습득
          - 타 포지션 개발자와 이야기 하면서 부족한 다른 분야의 개발 지식에 대한 배경 지식 상승
          - 같은 포지션 개발자와 프로젝트를 하며 생기는 오류를 같이 이야기 해보고 어느 기술이 좋을지 논의하며 백엔드 기술의 배경지식 상승
          - 2022 구글 I/O 시청 이벤트를 참여하여 차세대 미래에 중요시 여겨지는 기술 동향을 파악. 또, 구글의 취약 계층 , 편견 , 환경을 대주제로 문제를 해결해 나가는 모습을 보고 사회적 책임감을 느낄 수 있었음
          - 타 GDSC 와 연합 활동으로 [커리어 세션](https://gdsc.community.dev/events/details/developer-student-clubs-daejin-university-presents-gdsc-career-harugan-gugeuleul-muryoceheom-haeboseyo/) 등을 운영 스태프로 참가
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Daejin University
        caption: 2017 - Present
        sub_title: 산업경영공학 | 컴퓨터공학
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
         - 대진대학교에 다니는 동안 다수의 팀 프로젝트, 협업 능력 , 사회관계 등에 대해 배웠습니다. 
         - 주전공인 산업경영공학에서 진행한 다수의 Term Project는 더 나은 상호작용에 대해 알아가게끔 했습니다. 
         - 복수전공인 컴퓨터 공학에서는 백엔드 개발자로 진로를 잡은 저에게 있어 부족한 CS 지식을 채워주었습니다. 

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
